name: coffre
services:
  nginx:
    container_name: coffre-nginx
    image: nginx:1.27-alpine
    volumes:
      - ./.docker/nginx/conf:/etc/nginx/conf.d:ro
      - .:/var/www/html:rw
    ports:
      - ${NGINX_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      - php
    links:
      - php
  php:
    container_name: coffre-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./.docker/php/conf:/usr/local/etc/php/conf.d:rw
      - .:/var/www/html:rw
      - /var/www/html/storage
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    container_name: coffre-postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_DATABASE:-name}
      - POSTGRES_USER=${DB_USERNAME:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-pass}
      - TEST_DB=${DB_DATABASE_TEST:-test}
    volumes:
      - ./.docker/postgres/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
